version: '2'
services:
  influxdb:
    image: "tutum/influxdb"
    volumes:
      - "/home/rancher/influxdb/data:/data"
    ports:
      - 8083:8083
      - 8086:8086
  grafana:
    image: "grafana/grafana"
    volumes:
      - "/home/rancher/grafana/lib/grafana:/var/lib/grafana"
      - "/home/rancher/grafana/etc/grafana:/etc/grafana"
    links:
      - influxdb
    ports:
      - 3000:3000
  harpy:
    image: "feanil/harpy"
    links:
      - influxdb

